#board.py
"""
Board module
Inspired off of code generated by Copilot using Claude Sonnet 5 on 9/11/26 at 11 AM.
All the code below, aside from comments and a few edits to names/formatting, was generated by CoPilot.
I, Aidan Prather, read through the code, commented parts explaining functionality, and verified the logic.
"""

class Board:
    """Holds minesweeper grid state and game logic."""

    def __init__(self, size, mine_count):
        # initialize key variables for the board state
        self.size = size
        self.mine_count = mine_count
        self.mines = set() # store all the currently placed mines
        
        # create lists stroing bool values for the state of each cell
        self.counts = [[0] * size for _ in range(size)]
        self.revealed = [[False] * size for _ in range(size)]
        self.flagged = [[False] * size for _ in range(size)]
        
        # used for key board states (beginning of the game, flags, etc.)
        self.mines_placed = False
        self.game_over = False
        self.won = False
        self.revealed_count = 0

    # calculate neighbors for a given cell
    def _neighbors(self, r, c):
        for dr in (-1, 0, 1):
            for dc in (-1, 0, 1):
                if dr == 0 and dc == 0:
                    continue
                nr, nc = r + dr, c + dc
                if 0 <= nr < self.size and 0 <= nc < self.size:
                    yield nr, nc

    # place mines on the board, avoiding the initial safe cell and its neighbors (call after the first square is revealed)
    def _place_mines(self, safe_r, safe_c):
        # determine which cells are forbidden for mine placement (initial safe cell and its neighbors)
        forbidden = {(safe_r, safe_c)}
        forbidden.update(self._neighbors(safe_r, safe_c))
        cells = [
            (r, c)
            for r in range(self.size)
            for c in range(self.size)
            if (r, c) not in forbidden
        ]
        # randomly place mines in allowed cells
        self.mines = set(random.sample(cells, self.mine_count))
        # update counts for neighboring cells
        for r, c in self.mines:
            for nr, nc in self._neighbors(r, c):
                self.counts[nr][nc] += 1
        self.mines_placed = True

    # reveal a cell and recursively reveal neighboring cells if the count is zero
    def reveal(self, r, c):
        # ignore irrelavent game states
        if self.game_over or self.flagged[r][c] or self.revealed[r][c]:
            return

        # if this is the first move, place mines avoiding this cell
        if not self.mines_placed:
            self._place_mines(r, c)

        if (r, c) in self.mines:
            self.revealed[r][c] = True
            self.game_over = True
            self.won = False
            return

        # flood fill using stack for zero-count cells
        stack = [(r, c)]
        while stack:
            cr, cc = stack.pop()
            if self.revealed[cr][cc] or self.flagged[cr][cc]:
                continue
            self.revealed[cr][cc] = True
            self.revealed_count += 1
            if self.counts[cr][cc] == 0:
                # add all non-revealed, non-mine neighbors to the stack for further revealing
                for nr, nc in self._neighbors(cr, cc):
                    if not self.revealed[nr][nc] and (nr, nc) not in self.mines:
                        stack.append((nr, nc))

        # check if the player has won after revealing cells
        total_safe = self.size * self.size - self.mine_count
        if self.revealed_count >= total_safe:
            self.game_over = True
            self.won = True

    def chord(self, r, c):
        """Reveal neighbors of a revealed numbered cell if flag count matches."""
        if not self.revealed[r][c] or self.counts[r][c] == 0:
            return
        neighbors = list(self._neighbors(r, c))
        flags = sum(1 for nr, nc in neighbors if self.flagged[nr][nc])
        if flags == self.counts[r][c]:
            for nr, nc in neighbors:
                if not self.flagged[nr][nc] and not self.revealed[nr][nc]:
                    self.reveal(nr, nc)
                    if self.game_over:
                        return

    # toggle a flag on a cell, ignoring revealed cells and game over state
    def toggle_flag(self, r, c):
        if self.game_over or self.revealed[r][c]:
            return
        self.flagged[r][c] = not self.flagged[r][c]

    def flags_placed(self):
        return sum(sum(row) for row in self.flagged)
