#button.py
"""
Board module
Inspired off of code generated by Copilot using Claude Sonnet 5 on 9/11/26 at 11 AM.
All the code below, aside from comments and a few edits to names/formatting, was generated by CoPilot.
I, Warren Tan, read through the code, commented parts explaining functionality, and verified the logic.
"""

# import modules
import pygame

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Colors
COLOR_TEXT = (240, 240, 240)
COLOR_BUTTON = (70, 130, 180)
COLOR_BUTTON_HOVER = (100, 160, 210)

# ---------------------------------------------------------------------------
# Button Class Definition
# ---------------------------------------------------------------------------

class Button:
    """Renders interactable rectangles"""

    def __init__(self, rect, text, font):
        self.rect = pygame.Rect(rect)
        self.text = text
        self.font = font

    # draws the button onto the designated surface
    def draw(self, surface):
        # changes colour to COLOR_BUTTON_HOVER if hovered
        hovered = self.rect.collidepoint(pygame.mouse.get_pos())
        color = COLOR_BUTTON_HOVER if hovered else COLOR_BUTTON

        # draw rectangle and text, if applicable
        pygame.draw.rect(surface, color, self.rect, border_radius=6)
        pygame.draw.rect(surface, COLOR_TEXT, self.rect, width=2, border_radius=6)
        label = self.font.render(self.text, True, COLOR_TEXT)

        # copy the rendered label onto the preexisting button
        surface.blit(label, label.get_rect(center=self.rect.center))

    # returns true if clicked
    def is_clicked(self, pos):
        return self.rect.collidepoint(pos)