# main.py
"""
Main Game Module
Inspired off of code generated by Copilot using Claude Sonnet 5 on 9/11/26 at 11 AM.
All the code below, aside from comments and a few edits to names/formatting, was generated by CoPilot.
I, Warren Tan, read through the code, commented parts explaining functionality, and verified the logic.

This file contains the main loop for the gameplay using the game class. All player input is handled through here, 
and the UI elements are  outputted corresponding to the state of the game.
"""

# import modules
import sys
import pygame
from board import Board
from button import Button

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# 10x10 grid
GRID_SIZE = 10

# pixel sizes of cell, hud, and window
CELL_SIZE = 50
HUD_HEIGHT = 60
BOARD_PIXELS = GRID_SIZE * CELL_SIZE
WINDOW_WIDTH = BOARD_PIXELS
WINDOW_HEIGHT = BOARD_PIXELS + HUD_HEIGHT

# range of number of mines on board creation
MIN_MINES = 10
MAX_MINES = 20

# framerate of the game
FPS = 60

# Colors
COLOR_BG = (30, 30, 30)
COLOR_GRID_LINE = (60, 60, 60)
COLOR_HIDDEN = (120, 120, 120)
COLOR_HIDDEN_HOVER = (140, 140, 140)
COLOR_REVEALED = (200, 200, 200)
COLOR_FLAG = (220, 60, 60)
COLOR_MINE = (20, 20, 20)
COLOR_MINE_BG = (220, 60, 60)
COLOR_TEXT = (240, 240, 240)
COLOR_TITLE = (250, 200, 60)

# colour values of the # of adjacent mines text
NUMBER_COLORS = {
    1: (50, 90, 220),
    2: (50, 150, 50),
    3: (220, 50, 50),
    4: (30, 30, 140),
    5: (140, 30, 30),
    6: (40, 150, 150),
    7: (20, 20, 20),
    8: (100, 100, 100),
}

# game state names
STATE_TITLE = "title"
STATE_SETTINGS = "settings"
STATE_GAME = "game"

# ---------------------------------------------------------------------------
# Game application
# ---------------------------------------------------------------------------

class Game:
    """Main game """

    def __init__(self):
        # starts pygame
        pygame.init()

        # pygame application name
        pygame.display.set_caption("Minesweeper")

        # sets window width and height
        self.screen = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))

        # initialise clock
        self.clock = pygame.time.Clock()

        # set game fonts
        self.font_title = pygame.font.SysFont("Ubuntu Condensed", 64, bold=True)
        self.font_large = pygame.font.SysFont("Ubuntu Condensed", 32, bold=True)
        self.font_medium = pygame.font.SysFont("Ubuntu Condensed", 24)
        self.font_small = pygame.font.SysFont("Ubuntu Condensed", 18)
        self.font_cell = pygame.font.SysFont("Ubuntu Condensed", 18, bold=True)

        # initial game state
        self.state = STATE_TITLE
        self.mine_count = 15
        self.board = None

        # clock variables
        self.start_ticks = 0
        self.elapsed_seconds = 0

        # render buttons in initial game states
        self._build_title_buttons()
        self._build_settings_buttons()
        self._build_game_buttons()

    # -- button setup -------------------------------------------------------
    
    # Title Buttons
    def _build_title_buttons(self):
        # window horizontal center
        cx = WINDOW_WIDTH // 2

        # Title state buttons
        self.play_button = Button((cx - 100, 300, 200, 55), "Play", self.font_large)
        self.quit_button = Button((cx - 100, 380, 200, 55), "Quit", self.font_large)

    # Settings Buttons
    def _build_settings_buttons(self):
        # window horizontal center
        cx = WINDOW_WIDTH // 2

        # Settings state buttons
        self.minus_button = Button((cx - 140, 300, 50, 50), "-", self.font_large)
        self.plus_button = Button((cx + 90, 300, 50, 50), "+", self.font_large)
        self.start_button = Button((cx - 100, 400, 200, 55), "Start", self.font_large)
        self.back_button = Button((cx - 100, 470, 200, 45), "Back", self.font_medium)

    # Game Buttons
    def _build_game_buttons(self):
        self.restart_button = Button((WINDOW_WIDTH - 145, 10, 65, 40), "Reset", self.font_medium)
        self.menu_button = Button((WINDOW_WIDTH - 70, 10, 65, 40), "Menu", self.font_medium)

    # -- state transitions --------------------------------------------------
    
    # initialise a new game board
    def start_new_game(self):
        # builds board with mine_count # of mines
        self.board = Board(GRID_SIZE, self.mine_count)

        # initialise trackers for timer
        self.start_ticks = pygame.time.get_ticks()
        self.elapsed_seconds = 0

        # set game state to STATE_GAME
        self.state = STATE_GAME

    # -- drawing functions --------------------------------------------------

    # draws screens based on state variable
    def draw(self):
        self.screen.fill(COLOR_BG)
        if self.state == STATE_TITLE:
            self.draw_title()
        elif self.state == STATE_SETTINGS:
            self.draw_settings()
        elif self.state == STATE_GAME:
            self.draw_game()

    # draws title screen
    def draw_title(self):
        # render and draw game title
        title = self.font_title.render("MINESWEEPER", True, COLOR_TITLE)
        self.screen.blit(title, title.get_rect(center=(WINDOW_WIDTH // 2, 180)))

        # render and draw subtitle/description
        subtitle = self.font_small.render("A classic puzzle game", True, COLOR_TEXT)
        self.screen.blit(subtitle, subtitle.get_rect(center=(WINDOW_WIDTH // 2, 230)))

        # draw pre-rendered buttons
        # rendered in _build_title_buttons
        self.play_button.draw(self.screen)
        self.quit_button.draw(self.screen)

    # draws settings screen
    def draw_settings(self):
        # render and draw 'Game Settings' text
        title = self.font_large.render("Game Settings", True, COLOR_TEXT)
        self.screen.blit(title, title.get_rect(center=(WINDOW_WIDTH // 2, 150)))

        # render and draw 'Number of Mines' text
        label = self.font_medium.render("Number of Mines", True, COLOR_TEXT)
        self.screen.blit(label, label.get_rect(center=(WINDOW_WIDTH // 2, 250)))

        # draw pre-rendered buttons
        # rendered in _build_settings_buttons
        self.minus_button.draw(self.screen)
        self.plus_button.draw(self.screen)

        # render and draw number of mines setting
        count_text = self.font_large.render(str(self.mine_count), True, COLOR_TITLE)
        self.screen.blit(count_text, count_text.get_rect(center=(WINDOW_WIDTH // 2, 325)))

        # render and draw the valid range of mine count
        range_text = self.font_small.render(
            f"(range {MIN_MINES}-{MAX_MINES})", True, COLOR_TEXT
        )
        self.screen.blit(range_text, range_text.get_rect(center=(WINDOW_WIDTH // 2, 360)))

        # draw pre-rendered buttons
        # rendered in _build_settings_buttons
        self.start_button.draw(self.screen)
        self.back_button.draw(self.screen)

    # draws game screen
    def draw_game(self):
        # draw hud and board
        self.draw_hud()
        self.draw_board()

        # draw overlay upon game over
        if self.board.game_over:
            self.draw_game_over_overlay()

    # draws game hud (above game board)
    def draw_hud(self):
        # render and draw hud area
        # contains information for the current mines on the board and elapsed time (time since game start)
        pygame.draw.rect(self.screen, (45, 45, 45), (0, 0, WINDOW_WIDTH, HUD_HEIGHT))
        mines_left = self.board.mine_count - self.board.flags_placed()
        mine_text = self.font_medium.render(f"Mines: {mines_left}", True, COLOR_TEXT)
        self.screen.blit(mine_text, (10, 15))
        time_text = self.font_medium.render(f"Time: {self.elapsed_seconds}", True, COLOR_TEXT)
        self.screen.blit(time_text, (WINDOW_WIDTH // 2 - 50, 15))

        # draw pre-rendered buttons
        # rendered in _build_game_buttons
        self.restart_button.draw(self.screen)
        self.menu_button.draw(self.screen)

    # draws game board (below game hud)
    def draw_board(self):
        # draws initialised square board of size GRID_SIZE
        # initialised in start_new_game
        board = self.board

        # get position of player mouse
        mouse_pos = pygame.mouse.get_pos()

        # render and draw each cell (amount based off board size)
        for r in range(board.size):
            for c in range(board.size):
                x = c * CELL_SIZE
                y = HUD_HEIGHT + r * CELL_SIZE
                rect = pygame.Rect(x, y, CELL_SIZE, CELL_SIZE)

                # if mine is 
                is_mine = (r, c) in board.mines

                # cell rendering
                # cell is revealed
                if board.revealed[r][c]:
                    # revealed cell is a mine
                    if is_mine:
                        # draw cell of colour COLOR_MINE_BG
                        pygame.draw.rect(self.screen, COLOR_MINE_BG, rect)

                        # draw mine indicator
                        pygame.draw.circle(self.screen, COLOR_MINE, rect.center, CELL_SIZE // 4)

                    # revealed cell is not a mine
                    else:
                        # draw cell of colour COLOR_REVEALED
                        pygame.draw.rect(self.screen, COLOR_REVEALED, rect)

                        # render and draw the number of adjacent mines
                        # changes colour of text based off number (in NUMBER_COLORS)
                        # does not render any text if there are no adjacent mines
                        count = board.counts[r][c]
                        if count > 0:
                            color = NUMBER_COLORS.get(count, COLOR_TEXT)
                            num_surf = self.font_cell.render(str(count), True, color)
                            self.screen.blit(num_surf, num_surf.get_rect(center=rect.center))

                # cell is not revealed
                else:
                    # change cell colour on hover
                    hovered = rect.collidepoint(mouse_pos) and not board.game_over
                    color = COLOR_HIDDEN_HOVER if hovered else COLOR_HIDDEN
                    pygame.draw.rect(self.screen, color, rect)

                    # cell is flagged 
                    if board.flagged[r][c]:
                        # render and draw flag
                        flag_points = [
                            (rect.left + 8, rect.top + 5),
                            (rect.left + 8, rect.bottom - 5),
                            (rect.left + CELL_SIZE - 6, rect.top + rect.height // 2),
                        ]
                        pygame.draw.polygon(self.screen, COLOR_FLAG, flag_points)

                    # game is over. reveal (unflagged) mines
                    elif board.game_over and is_mine:
                        pygame.draw.circle(self.screen, COLOR_MINE, rect.center, CELL_SIZE // 4)

                # cell border
                pygame.draw.rect(self.screen, COLOR_GRID_LINE, rect, width=1)

    # draw game over screen
    def draw_game_over_overlay(self):
        # render and draw overlay to indicate game over
        overlay = pygame.Surface((WINDOW_WIDTH, WINDOW_HEIGHT), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 150))
        self.screen.blit(overlay, (0, 0))

        # render and draw end text
        # display 'You Win!' upon victory, 'Game Over' upon defeat
        message = "You Win!" if self.board.won else "Game Over"
        color = (80, 220, 80) if self.board.won else (220, 60, 60)
        text = self.font_title.render(message, True, color)
        self.screen.blit(text, text.get_rect(center=(WINDOW_WIDTH // 2, WINDOW_HEIGHT // 2 - 40)))

        # render and draw user instructions
        hint = self.font_small.render(
            "Press R to restart or M for menu", True, COLOR_TEXT
        )
        self.screen.blit(hint, hint.get_rect(center=(WINDOW_WIDTH // 2, WINDOW_HEIGHT // 2 + 20)))

    
    # -- main loop ----------------------------------------------------------
    def run(self):
        while True:
            for event in pygame.event.get():
                self.handle_event(event)

            if self.state == STATE_GAME and self.board and not self.board.game_over:
                self.elapsed_seconds = (pygame.time.get_ticks() - self.start_ticks) // 1000

            self.draw()
            pygame.display.flip()
            self.clock.tick(FPS)

    def handle_event(self, event):
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        # handles user click based of what screen they are on (title, setting, actie board)
        if event.type == pygame.MOUSEBUTTONDOWN:
            if self.state == STATE_TITLE:
                self.handle_title_click(event.pos)
            elif self.state == STATE_SETTINGS:
                self.handle_settings_click(event.pos)
            elif self.state == STATE_GAME:
                self.handle_game_click(event.pos, event.button)
        # handles user key input. Pressing the escape key leads to the main menu
        # if the game is over, the r key starts a new game and the m key returns to the menu
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                if self.state == STATE_GAME:
                    self.state = STATE_TITLE
                elif self.state == STATE_SETTINGS:
                    self.state = STATE_TITLE
            elif self.state == STATE_GAME and self.board and self.board.game_over:
                if event.key == pygame.K_r:
                    self.start_new_game()
                elif event.key == pygame.K_m:
                    self.state = STATE_TITLE

    # while on the title screen, chech to see if the settings or quit button is clicked
    def handle_title_click(self, pos):
        if self.play_button.is_clicked(pos):
            self.state = STATE_SETTINGS
        elif self.quit_button.is_clicked(pos):
            pygame.quit()
            sys.exit()

    # while setting up a new game, the user can select 10-20 mines, or exit back to title
    def handle_settings_click(self, pos):
        if self.minus_button.is_clicked(pos):
            self.mine_count = max(MIN_MINES, self.mine_count - 1)
        elif self.plus_button.is_clicked(pos):
            self.mine_count = min(MAX_MINES, self.mine_count + 1)
        elif self.start_button.is_clicked(pos):
            self.start_new_game()
        elif self.back_button.is_clicked(pos):
            self.state = STATE_TITLE

    # handles user input while the minesweeper board is active
    def handle_game_click(self, pos, button):
        x, y = pos
        if self.restart_button.is_clicked(pos):
            self.start_new_game()
            return
        if self.menu_button.is_clicked(pos):
            self.state = STATE_TITLE
            return
        # checks for input on the minesweeper grid
        if y < HUD_HEIGHT:
            return
        col = x // CELL_SIZE
        row = (y - HUD_HEIGHT) // CELL_SIZE
        if not (0 <= row < GRID_SIZE and 0 <= col < GRID_SIZE):
            return

        if self.board.game_over:
            return

        if button == 1:  # left click, reveal a tile
            if self.board.revealed[row][col]:
                self.board.chord(row, col)
            else:
                self.board.reveal(row, col)
        elif button == 3:  # right click, flag a tile
            self.board.toggle_flag(row, col)
    


# run the game
def main():
    Game().run()

if __name__ == "__main__":
    main()